import type { ScenarioRequest } from './types'

export type GoldenMaster = {
  id: string
  name: string
  description: string
  scenario: ScenarioRequest
}

export const goldenMasters: GoldenMaster[] = [
  {
    id: 'gm-01-saas-baseline',
    name: 'SaaS baseline',
    description: 'Standard multi-tenant SaaS with moderate traffic and standard SLOs',
    scenario: {
      name: 'SaaS baseline',
      description: 'Standard multi-tenant SaaS with moderate traffic and standard SLOs',
      productType: 'SAAS_B2B',
      workload: {
        registeredUsers: 50000,
        dailyActiveUsers: 12000,
        concurrentUsers: 600,
        averageRps: 90,
        peakRps: 540,
        burstFactor: 6,
        readPercentage: 82,
        writePercentage: 18,
        averagePayloadBytes: 4096,
        maximumPayloadBytes: 1800000,
        batchJobsPerDay: 2,
        asynchronousWorkPercentage: 15,
      },
      data: {
        currentStorageGb: 90,
        monthlyGrowthPercentage: 7,
        retentionMonths: 24,
        objectStorageGb: 45,
        hotDataPercentage: 30,
        eventVolumePerDay: 320000,
      },
      quality: {
        targetP50Ms: 85,
        targetP95Ms: 260,
        targetP99Ms: 750,
        availabilitySloPercent: 99.9,
        rtoMinutes: 60,
        rpoMinutes: 15,
        consistencyLevel: 'READ_YOUR_WRITES',
        geographicScope: 'MULTI_COUNTRY',
      },
      organization: {
        teamSize: 6,
        operationsMaturity: 'MEDIUM',
        deploymentFrequencyPerWeek: 4,
        onCallAvailable: true,
        observabilityMaturity: 'MEDIUM',
        cloudExperience: 'MEDIUM',
        budgetBand: 'MODERATE',
      },
      deployment: {
        serverType: 'CONTAINER',
        cloudProvider: 'AWS',
        deploymentService: 'EKS',
        gatewayType: 'ALB',
        loadBalancerType: 'NLB',
        minimumUnitMemoryMb: 4096,
        minimumUnitCpuCount: 2,
        serviceTopology: {
          totalServices: 5,
          microservicesCount: 2,
          scalableServicesCount: 2,
          services: [
            { serviceName: 'api', requestsPerMinute: 1100, memoryMb: 2048, cpuCount: 1, replicas: 3, serverBinding: 'SHARED' },
            { serviceName: 'worker', requestsPerMinute: 350, memoryMb: 1024, cpuCount: 1, replicas: 2, serverBinding: 'SHARED' },
          ],
        },
      },
    },
  },
  {
    id: 'gm-02-ecommerce-growth',
    name: 'E-commerce growth',
    description: 'High-read e-commerce catalog with flash-sale bursts',
    scenario: {
      name: 'E-commerce growth',
      description: 'High-read e-commerce catalog with flash-sale bursts',
      productType: 'ECOMMERCE',
      workload: {
        registeredUsers: 250000,
        dailyActiveUsers: 80000,
        concurrentUsers: 5000,
        averageRps: 220,
        peakRps: 1800,
        burstFactor: 8.18,
        readPercentage: 94,
        writePercentage: 6,
        averagePayloadBytes: 2048,
        maximumPayloadBytes: 1200000,
        batchJobsPerDay: 8,
        asynchronousWorkPercentage: 25,
      },
      data: {
        currentStorageGb: 220,
        monthlyGrowthPercentage: 12,
        retentionMonths: 12,
        objectStorageGb: 120,
        hotDataPercentage: 45,
        eventVolumePerDay: 900000,
      },
      quality: {
        targetP50Ms: 70,
        targetP95Ms: 220,
        targetP99Ms: 650,
        availabilitySloPercent: 99.95,
        rtoMinutes: 30,
        rpoMinutes: 5,
        consistencyLevel: 'EVENTUAL',
        geographicScope: 'GLOBAL',
      },
      organization: {
        teamSize: 18,
        operationsMaturity: 'HIGH',
        deploymentFrequencyPerWeek: 12,
        onCallAvailable: true,
        observabilityMaturity: 'HIGH',
        cloudExperience: 'HIGH',
        budgetBand: 'FLEXIBLE',
      },
      deployment: {
        serverType: 'CONTAINER',
        cloudProvider: 'AWS',
        deploymentService: 'EKS',
        gatewayType: 'CLOUDFLARE',
        loadBalancerType: 'ALB',
        minimumUnitMemoryMb: 8192,
        minimumUnitCpuCount: 4,
        serviceTopology: {
          totalServices: 10,
          microservicesCount: 6,
          scalableServicesCount: 6,
          services: [
            { serviceName: 'storefront', requestsPerMinute: 4200, memoryMb: 4096, cpuCount: 2, replicas: 6, serverBinding: 'DEDICATED' },
            { serviceName: 'catalog', requestsPerMinute: 2800, memoryMb: 6144, cpuCount: 2, replicas: 5, serverBinding: 'DEDICATED' },
            { serviceName: 'cart', requestsPerMinute: 900, memoryMb: 2048, cpuCount: 1, replicas: 3, serverBinding: 'SHARED' },
            { serviceName: 'payment', requestsPerMinute: 180, memoryMb: 1024, cpuCount: 1, replicas: 2, serverBinding: 'DEDICATED' },
            { serviceName: 'search', requestsPerMinute: 1200, memoryMb: 8192, cpuCount: 4, replicas: 3, serverBinding: 'DEDICATED' },
          ],
        },
      },
    },
  },
  {
    id: 'gm-03-banking-api',
    name: 'Banking API',
    description: 'Regulated banking backend with strict latency and consistency requirements',
    scenario: {
      name: 'Banking API',
      description: 'Regulated banking backend with strict latency and consistency requirements',
      productType: 'BANKING_API',
      workload: {
        registeredUsers: 1200000,
        dailyActiveUsers: 250000,
        concurrentUsers: 8000,
        averageRps: 180,
        peakRps: 1400,
        burstFactor: 7.77,
        readPercentage: 70,
        writePercentage: 30,
        averagePayloadBytes: 8192,
        maximumPayloadBytes: 5000000,
        batchJobsPerDay: 48,
        asynchronousWorkPercentage: 35,
      },
      data: {
        currentStorageGb: 1800,
        monthlyGrowthPercentage: 4,
        retentionMonths: 120,
        objectStorageGb: 900,
        hotDataPercentage: 60,
        eventVolumePerDay: 450000,
      },
      quality: {
        targetP50Ms: 45,
        targetP95Ms: 140,
        targetP99Ms: 400,
        availabilitySloPercent: 99.99,
        rtoMinutes: 15,
        rpoMinutes: 0,
        consistencyLevel: 'STRONG',
        geographicScope: 'MULTI_COUNTRY',
      },
      organization: {
        teamSize: 35,
        operationsMaturity: 'HIGH',
        deploymentFrequencyPerWeek: 3,
        onCallAvailable: true,
        observabilityMaturity: 'HIGH',
        cloudExperience: 'MEDIUM',
        budgetBand: 'FLEXIBLE',
      },
      deployment: {
        serverType: 'CONTAINER',
        cloudProvider: 'AZURE',
        deploymentService: 'APP_SERVICE',
        gatewayType: 'NLB',
        loadBalancerType: 'NLB',
        minimumUnitMemoryMb: 8192,
        minimumUnitCpuCount: 4,
        serviceTopology: {
          totalServices: 14,
          microservicesCount: 9,
          scalableServicesCount: 8,
          services: [
            { serviceName: 'accounts', requestsPerMinute: 1600, memoryMb: 8192, cpuCount: 4, replicas: 6, serverBinding: 'DEDICATED' },
            { serviceName: 'ledger', requestsPerMinute: 900, memoryMb: 12288, cpuCount: 4, replicas: 5, serverBinding: 'DEDICATED' },
            { serviceName: 'notifications', requestsPerMinute: 600, memoryMb: 2048, cpuCount: 2, replicas: 4, serverBinding: 'SHARED' },
            { serviceName: 'fraud', requestsPerMinute: 220, memoryMb: 4096, cpuCount: 2, replicas: 3, serverBinding: 'DEDICATED' },
          ],
        },
      },
    },
  },
  {
    id: 'gm-04-search-platform',
    name: 'Search platform',
    description: 'Document and product search with heavy indexing and read traffic',
    scenario: {
      name: 'Search platform',
      description: 'Document and product search with heavy indexing and read traffic',
      productType: 'SEARCH_PLATFORM',
      workload: {
        registeredUsers: 900000,
        dailyActiveUsers: 180000,
        concurrentUsers: 12000,
        averageRps: 350,
        peakRps: 2600,
        burstFactor: 7.43,
        readPercentage: 92,
        writePercentage: 8,
        averagePayloadBytes: 512,
        maximumPayloadBytes: 500000,
        batchJobsPerDay: 36,
        asynchronousWorkPercentage: 45,
      },
      data: {
        currentStorageGb: 3400,
        monthlyGrowthPercentage: 18,
        retentionMonths: 36,
        objectStorageGb: 2100,
        hotDataPercentage: 25,
        eventVolumePerDay: 2400000,
      },
      quality: {
        targetP50Ms: 60,
        targetP95Ms: 180,
        targetP99Ms: 500,
        availabilitySloPercent: 99.95,
        rtoMinutes: 20,
        rpoMinutes: 15,
        consistencyLevel: 'EVENTUAL',
        geographicScope: 'GLOBAL',
      },
      organization: {
        teamSize: 22,
        operationsMaturity: 'HIGH',
        deploymentFrequencyPerWeek: 8,
        onCallAvailable: true,
        observabilityMaturity: 'HIGH',
        cloudExperience: 'HIGH',
        budgetBand: 'FLEXIBLE',
      },
      deployment: {
        serverType: 'CONTAINER',
        cloudProvider: 'GCP',
        deploymentService: 'CLOUD_RUN',
        gatewayType: 'CLOUDFLARE',
        loadBalancerType: 'NLB',
        minimumUnitMemoryMb: 16384,
        minimumUnitCpuCount: 8,
        serviceTopology: {
          totalServices: 9,
          microservicesCount: 5,
          scalableServicesCount: 7,
          services: [
            { serviceName: 'ingest', requestsPerMinute: 1500, memoryMb: 16384, cpuCount: 8, replicas: 12, serverBinding: 'DEDICATED' },
            { serviceName: 'indexer', requestsPerMinute: 900, memoryMb: 24576, cpuCount: 8, replicas: 8, serverBinding: 'DEDICATED' },
            { serviceName: 'query', requestsPerMinute: 3600, memoryMb: 8192, cpuCount: 4, replicas: 10, serverBinding: 'DEDICATED' },
            { serviceName: 'suggest', requestsPerMinute: 1200, memoryMb: 4096, cpuCount: 2, replicas: 5, serverBinding: 'SHARED' },
          ],
        },
      },
    },
  },
  {
    id: 'gm-05-mobile-social',
    name: 'Mobile social',
    description: 'Mobile-first social feed with media uploads and high async traffic',
    scenario: {
      name: 'Mobile social',
      description: 'Mobile-first social feed with media uploads and high async traffic',
      productType: 'MOBILE_APPLICATION',
      workload: {
        registeredUsers: 400000,
        dailyActiveUsers: 160000,
        concurrentUsers: 18000,
        averageRps: 280,
        peakRps: 2200,
        burstFactor: 7.86,
        readPercentage: 78,
        writePercentage: 22,
        averagePayloadBytes: 6144,
        maximumPayloadBytes: 12000000,
        batchJobsPerDay: 12,
        asynchronousWorkPercentage: 55,
      },
      data: {
        currentStorageGb: 7500,
        monthlyGrowthPercentage: 22,
        retentionMonths: 6,
        objectStorageGb: 6200,
        hotDataPercentage: 15,
        eventVolumePerDay: 3800000,
      },
      quality: {
        targetP50Ms: 95,
        targetP95Ms: 280,
        targetP99Ms: 820,
        availabilitySloPercent: 99.9,
        rtoMinutes: 45,
        rpoMinutes: 60,
        consistencyLevel: 'EVENTUAL',
        geographicScope: 'GLOBAL',
      },
      organization: {
        teamSize: 26,
        operationsMaturity: 'MEDIUM',
        deploymentFrequencyPerWeek: 7,
        onCallAvailable: true,
        observabilityMaturity: 'MEDIUM',
        cloudExperience: 'HIGH',
        budgetBand: 'FLEXIBLE',
      },
      deployment: {
        serverType: 'CONTAINER',
        cloudProvider: 'AWS',
        deploymentService: 'ECS',
        gatewayType: 'KONG',
        loadBalancerType: 'NLB',
        minimumUnitMemoryMb: 8192,
        minimumUnitCpuCount: 4,
        serviceTopology: {
          totalServices: 11,
          microservicesCount: 6,
          scalableServicesCount: 8,
          services: [
            { serviceName: 'feed', requestsPerMinute: 3800, memoryMb: 6144, cpuCount: 2, replicas: 8, serverBinding: 'SHARED' },
            { serviceName: 'media', requestsPerMinute: 1400, memoryMb: 16384, cpuCount: 4, replicas: 10, serverBinding: 'SERVERLESS' },
            { serviceName: 'chat', requestsPerMinute: 900, memoryMb: 2048, cpuCount: 2, replicas: 6, serverBinding: 'SHARED' },
            { serviceName: 'ads', requestsPerMinute: 600, memoryMb: 3072, cpuCount: 2, replicas: 4, serverBinding: 'DEDICATED' },
          ],
        },
      },
    },
  },
  {
    id: 'gm-06-ml-metadata',
    name: 'Document AI metadata',
    description: 'Document ingestion pipeline with async processing and object storage',
    scenario: {
      name: 'Document AI metadata',
      description: 'Document ingestion pipeline with async processing and object storage',
      productType: 'DOCUMENT_AI',
      workload: {
        registeredUsers: 32000,
        dailyActiveUsers: 8500,
        concurrentUsers: 700,
        averageRps: 140,
        peakRps: 960,
        burstFactor: 6.86,
        readPercentage: 40,
        writePercentage: 60,
        averagePayloadBytes: 256000,
        maximumPayloadBytes: 25000000,
        batchJobsPerDay: 160,
        asynchronousWorkPercentage: 75,
      },
      data: {
        currentStorageGb: 1200,
        monthlyGrowthPercentage: 26,
        retentionMonths: 84,
        objectStorageGb: 980,
        hotDataPercentage: 20,
        eventVolumePerDay: 1400000,
      },
      quality: {
        targetP50Ms: 110,
        targetP95Ms: 340,
        targetP99Ms: 950,
        availabilitySloPercent: 99.9,
        rtoMinutes: 90,
        rpoMinutes: 60,
        consistencyLevel: 'READ_YOUR_WRITES',
        geographicScope: 'COUNTRY',
      },
      organization: {
        teamSize: 10,
        operationsMaturity: 'MEDIUM',
        deploymentFrequencyPerWeek: 4,
        onCallAvailable: false,
        observabilityMaturity: 'LOW',
        cloudExperience: 'MEDIUM',
        budgetBand: 'MODERATE',
      },
      deployment: {
        serverType: 'SERVERLESS',
        cloudProvider: 'GCP',
        deploymentService: 'CLOUD_RUN',
        gatewayType: 'CLOUDFLARE',
        loadBalancerType: 'CLB',
        minimumUnitMemoryMb: 2048,
        minimumUnitCpuCount: 1,
        serviceTopology: {
          totalServices: 7,
          microservicesCount: 4,
          scalableServicesCount: 5,
          services: [
            { serviceName: 'upload', requestsPerMinute: 500, memoryMb: 2048, cpuCount: 1, replicas: 20, serverBinding: 'SERVERLESS' },
            { serviceName: 'ocr', requestsPerMinute: 300, memoryMb: 4096, cpuCount: 2, replicas: 30, serverBinding: 'SERVERLESS' },
            { serviceName: 'index', requestsPerMinute: 700, memoryMb: 2048, cpuCount: 1, replicas: 15, serverBinding: 'SERVERLESS' },
          ],
        },
      },
    },
  },
  {
    id: 'gm-07-marketplace',
    name: 'Marketplace',
    description: 'Two-sided marketplace with buyers, sellers, and search-heavy browsing',
    scenario: {
      name: 'Marketplace',
      description: 'Two-sided marketplace with buyers, sellers, and search-heavy browsing',
      productType: 'MARKETPLACE',
      workload: {
        registeredUsers: 180000,
        dailyActiveUsers: 65000,
        concurrentUsers: 4000,
        averageRps: 170,
        peakRps: 1450,
        burstFactor: 8.53,
        readPercentage: 88,
        writePercentage: 12,
        averagePayloadBytes: 6144,
        maximumPayloadBytes: 3000000,
        batchJobsPerDay: 18,
        asynchronousWorkPercentage: 20,
      },
      data: {
        currentStorageGb: 560,
        monthlyGrowthPercentage: 10,
        retentionMonths: 18,
        objectStorageGb: 310,
        hotDataPercentage: 35,
        eventVolumePerDay: 710000,
      },
      quality: {
        targetP50Ms: 90,
        targetP95Ms: 240,
        targetP99Ms: 680,
        availabilitySloPercent: 99.95,
        rtoMinutes: 30,
        rpoMinutes: 10,
        consistencyLevel: 'READ_YOUR_WRITES',
        geographicScope: 'MULTI_COUNTRY',
      },
      organization: {
        teamSize: 14,
        operationsMaturity: 'MEDIUM',
        deploymentFrequencyPerWeek: 6,
        onCallAvailable: true,
        observabilityMaturity: 'MEDIUM',
        cloudExperience: 'MEDIUM',
        budgetBand: 'MODERATE',
      },
      deployment: {
        serverType: 'CONTAINER',
        cloudProvider: 'AWS',
        deploymentService: 'EKS',
        gatewayType: 'ALB',
        loadBalancerType: 'NLB',
        minimumUnitMemoryMb: 4096,
        minimumUnitCpuCount: 2,
        serviceTopology: {
          totalServices: 8,
          microservicesCount: 5,
          scalableServicesCount: 5,
          services: [
            { serviceName: 'catalog', requestsPerMinute: 2400, memoryMb: 4096, cpuCount: 2, replicas: 5, serverBinding: 'DEDICATED' },
            { serviceName: 'orders', requestsPerMinute: 700, memoryMb: 2048, cpuCount: 1, replicas: 4, serverBinding: 'DEDICATED' },
            { serviceName: 'payments', requestsPerMinute: 320, memoryMb: 2048, cpuCount: 1, replicas: 3, serverBinding: 'DEDICATED' },
            { serviceName: 'search', requestsPerMinute: 1100, memoryMb: 6144, cpuCount: 2, replicas: 4, serverBinding: 'DEDICATED' },
          ],
        },
      },
    },
  },
  {
    id: 'gm-08-iot-ingestion',
    name: 'IoT ingestion',
    description: 'High-volume device ingress with fan-out and cold retention',
    scenario: {
      name: 'IoT ingestion',
      description: 'High-volume device ingress with fan-out and cold retention',
      productType: 'IOT_INGESTION',
      workload: {
        registeredUsers: 800000,
        dailyActiveUsers: 720000,
        concurrentUsers: 2500,
        averageRps: 520,
        peakRps: 3400,
        burstFactor: 6.54,
        readPercentage: 20,
        writePercentage: 80,
        averagePayloadBytes: 256,
        maximumPayloadBytes: 65536,
        batchJobsPerDay: 96,
        asynchronousWorkPercentage: 85,
      },
      data: {
        currentStorageGb: 4200,
        monthlyGrowthPercentage: 31,
        retentionMonths: 6,
        objectStorageGb: 3800,
        hotDataPercentage: 10,
        eventVolumePerDay: 12000000,
      },
      quality: {
        targetP50Ms: 130,
        targetP95Ms: 420,
        targetP99Ms: 1100,
        availabilitySloPercent: 99.9,
        rtoMinutes: 120,
        rpoMinutes: 120,
        consistencyLevel: 'EVENTUAL',
        geographicScope: 'GLOBAL',
      },
      organization: {
        teamSize: 12,
        operationsMaturity: 'LOW',
        deploymentFrequencyPerWeek: 2,
        onCallAvailable: false,
        observabilityMaturity: 'LOW',
        cloudExperience: 'MEDIUM',
        budgetBand: 'MODERATE',
      },
      deployment: {
        serverType: 'CONTAINER',
        cloudProvider: 'AWS',
        deploymentService: 'ECS',
        gatewayType: 'NLB',
        loadBalancerType: 'NLB',
        minimumUnitMemoryMb: 2048,
        minimumUnitCpuCount: 1,
        serviceTopology: {
          totalServices: 6,
          microservicesCount: 3,
          scalableServicesCount: 4,
          services: [
            { serviceName: 'ingest', requestsPerMinute: 5800, memoryMb: 2048, cpuCount: 1, replicas: 16, serverBinding: 'SHARED' },
            { serviceName: 'router', requestsPerMinute: 3400, memoryMb: 4096, cpuCount: 2, replicas: 12, serverBinding: 'SHARED' },
            { serviceName: 'archive', requestsPerMinute: 1200, memoryMb: 1024, cpuCount: 1, replicas: 8, serverBinding: 'SHARED' },
          ],
        },
      },
    },
  },
  {
    id: 'gm-09-internal-crud',
    name: 'Internal CRUD',
    description: 'Small internal tooling with low traffic and simple operational needs',
    scenario: {
      name: 'Internal CRUD',
      description: 'Small internal tooling with low traffic and simple operational needs',
      productType: 'INTERNAL_CRUD',
      workload: {
        registeredUsers: 2200,
        dailyActiveUsers: 650,
        concurrentUsers: 80,
        averageRps: 12,
        peakRps: 55,
        burstFactor: 4.58,
        readPercentage: 75,
        writePercentage: 25,
        averagePayloadBytes: 1024,
        maximumPayloadBytes: 512000,
        batchJobsPerDay: 1,
        asynchronousWorkPercentage: 10,
      },
      data: {
        currentStorageGb: 18,
        monthlyGrowthPercentage: 3,
        retentionMonths: 24,
        objectStorageGb: 10,
        hotDataPercentage: 80,
        eventVolumePerDay: 15000,
      },
      quality: {
        targetP50Ms: 120,
        targetP95Ms: 320,
        targetP99Ms: 900,
        availabilitySloPercent: 99.5,
        rtoMinutes: 240,
        rpoMinutes: 180,
        consistencyLevel: 'READ_YOUR_WRITES',
        geographicScope: 'LOCAL',
      },
      organization: {
        teamSize: 3,
        operationsMaturity: 'LOW',
        deploymentFrequencyPerWeek: 1,
        onCallAvailable: false,
        observabilityMaturity: 'LOW',
        cloudExperience: 'LOW',
        budgetBand: 'MINIMAL',
      },
      deployment: {
        serverType: 'VM',
        cloudProvider: 'ON_PREM',
        deploymentService: 'VM_MANUAL',
        gatewayType: 'NGINX',
        loadBalancerType: 'NLB',
        minimumUnitMemoryMb: 1024,
        minimumUnitCpuCount: 1,
        serviceTopology: {
          totalServices: 2,
          microservicesCount: 0,
          scalableServicesCount: 0,
          services: [
            { serviceName: 'admin', requestsPerMinute: 50, memoryMb: 1024, cpuCount: 1, replicas: 1, serverBinding: 'SHARED' },
            { serviceName: 'reports', requestsPerMinute: 10, memoryMb: 512, cpuCount: 1, replicas: 1, serverBinding: 'SHARED' },
          ],
        },
      },
    },
  },
  {
    id: 'gm-10-streaming-metadata',
    name: 'Streaming metadata',
    description: 'Content metadata service for a streaming platform',
    scenario: {
      name: 'Streaming metadata',
      description: 'Content metadata service for a streaming platform',
      productType: 'STREAMING_METADATA',
      workload: {
        registeredUsers: 600000,
        dailyActiveUsers: 220000,
        concurrentUsers: 9000,
        averageRps: 260,
        peakRps: 1900,
        burstFactor: 7.31,
        readPercentage: 90,
        writePercentage: 10,
        averagePayloadBytes: 2048,
        maximumPayloadBytes: 2000000,
        batchJobsPerDay: 24,
        asynchronousWorkPercentage: 30,
      },
      data: {
        currentStorageGb: 1100,
        monthlyGrowthPercentage: 14,
        retentionMonths: 48,
        objectStorageGb: 600,
        hotDataPercentage: 35,
        eventVolumePerDay: 1600000,
      },
      quality: {
        targetP50Ms: 75,
        targetP95Ms: 210,
        targetP99Ms: 580,
        availabilitySloPercent: 99.95,
        rtoMinutes: 20,
        rpoMinutes: 10,
        consistencyLevel: 'READ_YOUR_WRITES',
        geographicScope: 'MULTI_COUNTRY',
      },
      organization: {
        teamSize: 16,
        operationsMaturity: 'MEDIUM',
        deploymentFrequencyPerWeek: 9,
        onCallAvailable: true,
        observabilityMaturity: 'MEDIUM',
        cloudExperience: 'HIGH',
        budgetBand: 'FLEXIBLE',
      },
      deployment: {
        serverType: 'CONTAINER',
        cloudProvider: 'AWS',
        deploymentService: 'EKS',
        gatewayType: 'CLOUDFLARE',
        loadBalancerType: 'NLB',
        minimumUnitMemoryMb: 6144,
        minimumUnitCpuCount: 4,
        serviceTopology: {
          totalServices: 7,
          microservicesCount: 4,
          scalableServicesCount: 5,
          services: [
            { serviceName: 'metadata', requestsPerMinute: 2600, memoryMb: 4096, cpuCount: 2, replicas: 6, serverBinding: 'DEDICATED' },
            { serviceName: 'recommendations', requestsPerMinute: 1800, memoryMb: 8192, cpuCount: 4, replicas: 6, serverBinding: 'DEDICATED' },
            { serviceName: 'encoding', requestsPerMinute: 500, memoryMb: 12288, cpuCount: 4, replicas: 8, serverBinding: 'SERVERLESS' },
            { serviceName: 'cdn-origin', requestsPerMinute: 1200, memoryMb: 2048, cpuCount: 2, replicas: 4, serverBinding: 'SHARED' },
          ],
        },
      },
    },
  },
]
